In [1]:
import pandas as pd

# Reading CSV files into DataFrames
batting_data = pd.read_csv('/kaggle/input/cricket/Batting_data.csv')
bowling_data = pd.read_csv('/kaggle/input/cricket/Bowling_data.csv')
fielding_data = pd.read_csv('/kaggle/input/cricket/Fielding_data.csv')
fantasy_data = pd.read_csv('/kaggle/input/cricket/Final_Fantasy_data.csv')
match_details = pd.read_csv('/kaggle/input/cricket/Match_details.csv')

In [2]:
# Merging Batting and Bowling data on match_id, season, fullName
batting_bowling_data = pd.merge(batting_data, bowling_data, 
                                on=['match_id', 'season', 'fullName', 'match_name', 'home_team', 'away_team', 'venue'], 
                                how='outer')

# Now, merge with Fielding data
combined_data = pd.merge(batting_bowling_data, fielding_data, 
                         on=['match_id', 'season', 'fullName', 'match_name', 'home_team', 'away_team', 'venue'], 
                         how='outer')

In [3]:
# Merge with Final Fantasy Data
full_data = pd.merge(combined_data, fantasy_data, 
                     on=['match_id', 'season', 'fullName', 'match_name', 'home_team', 'away_team', 'venue'], 
                     how='outer')

In [4]:
# Merge with Match Details
final_data = pd.merge(full_data, match_details, 
                      on=['match_id', 'season', 'match_name', 'venue', 'home_team', 'away_team'], 
                      how='outer')

In [5]:
# Example: Fill missing fantasy points with 0
final_data.fillna(0, inplace=True)

In [6]:
final_data.head(10)

,match_id,season,match_name,home_team,away_team,venue,bowling_team_x,batting_team_x,batting_innings_x,fullName,...,batting_innings_y,bowling_innings,Starting_11,Batting_FP_y,Bowling_FP_y,Fielding_FP_y,Total_FP,Dream Team,Captain,Vice Captain
0,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",0,0,0.0,Ajit Agarkar,...,1.0,2.0,4.0,0.0,81.0,6.0,91.0,1.0,0.0,1.0
1,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",KKR,RCB,2.0,Ashley Noffke,...,2.0,1.0,4.0,10.0,23.0,0.0,37.0,1.0,0.0,0.0
2,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",0,0,0.0,Ashok Dinda,...,1.0,2.0,4.0,0.0,64.0,0.0,68.0,1.0,0.0,0.0
3,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",KKR,RCB,2.0,Balachandra Akhil,...,2.0,1.0,4.0,-2.0,0.0,0.0,2.0,0.0,0.0,0.0
4,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",RCB,KKR,1.0,Brendon McCullum,...,1.0,2.0,4.0,216.0,0.0,8.0,228.0,1.0,1.0,0.0
5,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",KKR,RCB,2.0,Cameron White,...,2.0,1.0,4.0,4.0,0.0,8.0,16.0,0.0,0.0,0.0
6,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",RCB,KKR,1.0,David Hussey,...,1.0,2.0,4.0,13.0,0.0,0.0,17.0,0.0,0.0,0.0
7,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",0,0,0.0,Ishant Sharma,...,1.0,2.0,4.0,0.0,39.0,0.0,43.0,1.0,0.0,0.0
8,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",KKR,RCB,2.0,Jacques Kallis,...,2.0,1.0,4.0,10.0,21.0,8.0,43.0,1.0,0.0,0.0
9,335982,2008,RCB v KKR,RCB,KKR,"M.Chinnaswamy Stadium, Bengaluru",0,0,0.0,Laxmi Shukla,...,1.0,2.0,4.0,0.0,25.0,0.0,29.0,1.0,0.0,0.0

In [7]:
import pandas as pd

# Assuming you have a DataFrame called df with 'batting_team_x' and 'batting_team_y'
final_data['batting_team'] = final_data.apply(
    lambda row: row['batting_team_x'] if pd.notnull(row['batting_team_x']) and row['batting_team_x'] != 0
    else row['batting_team_y'], axis=1)

In [10]:



# Replace zeros in the 'team' column with corresponding 'bowling_team' values
final_data['team'] = final_data.apply(lambda row: row['bowling_team'] if row['team'] == 0 else row['team'], axis=1)

# Save the modified DataFrame back to a CSV file
final_data.to_csv('updated_file.csv', index=False)

In [8]:

# Create the new 'team' column with the logic:
final_data['team'] = final_data.apply(lambda row: row['batting_team_x'] if row['batting_position'] != 0 else row['bowling_team_y'], axis=1)

# Drop the unnecessary columns
final_data.drop(columns=['batting_team_x', 'batting_team_y', 'bowling_team_x', 'bowling_team_y'], inplace=True)

# Display the updated DataFrame
print(final_data.head())

   match_id  season match_name home_team away_team  \
0    335982    2008  RCB v KKR       RCB       KKR
1    335982    2008  RCB v KKR       RCB       KKR
2    335982    2008  RCB v KKR       RCB       KKR
3    335982    2008  RCB v KKR       RCB       KKR
4    335982    2008  RCB v KKR       RCB       KKR

                              venue  batting_innings_x           fullName  \
0  M.Chinnaswamy Stadium, Bengaluru                0.0       Ajit Agarkar
1  M.Chinnaswamy Stadium, Bengaluru                2.0      Ashley Noffke
2  M.Chinnaswamy Stadium, Bengaluru                0.0        Ashok Dinda
3  M.Chinnaswamy Stadium, Bengaluru                2.0  Balachandra Akhil
4  M.Chinnaswamy Stadium, Bengaluru                1.0   Brendon McCullum

   batting_position   runs  ...  bowling_innings  Starting_11  Batting_FP_y  \
0               0.0    0.0  ...              2.0          4.0           0.0
1               8.0    9.0  ...              1.0          4.0          10.0
2               0.0    0.0  ...              2.0          4.0           0.0
3               7.0    0.0  ...              1.0          4.0          -2.0
4               2.0  158.0  ...              2.0          4.0         216.0

   Bowling_FP_y  Fielding_FP_y  Total_FP  Dream Team  Captain  Vice Captain  \
0          81.0            6.0      91.0         1.0      0.0           1.0
1          23.0            0.0      37.0         1.0      0.0           0.0
2          64.0            0.0      68.0         1.0      0.0           0.0
3           0.0            0.0       2.0         0.0      0.0           0.0
4           0.0            8.0     228.0         1.0      1.0           0.0

   team
0   KKR
1   RCB
2   KKR
3   RCB
4   KKR

[5 rows x 52 columns]

In [11]:
final_data.to_csv("/kaggle/working/Merged_Fantasy_Team_Data.csv", index=False)